- job-template:
    name: "pipeline-{env}-deploy-transient"
    node: master
    logrotate:
       numToKeep: 20
    triggers:
      - timed: "H/30 * * * *"
    scm:
      - git:
          url: https://github.com/JioCloud/puppet-rjil.git
          branches:
            - 'master'
    builders:
      - shell:
          !include-raw deploy.sh
    publishers:
      - trigger-parameterized-builds:
          - project: "pipeline-{env}-test-transient"
            condition: UNSTABLE_OR_BETTER
            predefined-parameters: |
              deploy_id=${{BUILD_NUMBER}}
      - trigger-parameterized-builds:
          - project: "pipeline-{env}-test-transient"
            condition: FAILED
            predefined-parameters: |
              deploy_id=${{BUILD_NUMBER}}
              fail_immediately=1

- job-template:
    name: "pipeline-{env}-deploy"
    node: master
    logrotate:
       numToKeep: 20
    triggers:
      - timed: "H/30 * * * *"
    builders:
      - shell:
          !include-raw deploy.sh
    publishers:
      - trigger-parameterized-builds:
          - project: "pipeline-{env}-test"
            condition: UNSTABLE_OR_BETTER
            predefined-parameters: |
              deploy_id=${{BUILD_NUMBER}}

- job-template:
    name: "pipeline-{env}-test-transient"
    node: master
    parameters:
      - string:
          name: deploy_id
    logrotate:
       numToKeep: 20
    builders:
      - shell:
          !include-raw test.sh
    publishers:
      - trigger-parameterized-builds:
          - project: "pipeline-{env}-teardown"
            condition: ALWAYS
            current-parameters: true
#      - trigger-parameterized-builds:
#          - project: "{nextenv}-deploy"
#            condition: UNSTABLE_OR_BETTER
#            predefined-parameters: |
#              deploy_id=${{BUILD_NUMBER}}

- job-template:
    name: "pipeline-{env}-teardown"
    node: master
    parameters:
      - string:
          name: deploy_id
    logrotate:
       numToKeep: 20
    builders:
      - shell:
          !include-raw teardown.sh

- job-template:
    name: "pipeline-{env}-update"
    node: master
    parameters:
      - string:
          name: deploy_id
    logrotate:
       numToKeep: 20
    builders:
      - shell:
          !include-raw update.sh
    publishers:
      - trigger-parameterized-builds:
          - project: "pipeline-{env}-test"
            condition: UNSTABLE_OR_BETTER
            predefined-parameters: |
              deploy_id=${{BUILD_NUMBER}}

- job-template:
    name: "pipeline-{env}-test"
    node: master
    logrotate:
       numToKeep: 20
    builders:
      - shell:
          !include-raw test.sh
    publishers:
      - trigger-parameterized-builds:
          - project: "pipeline-{nextenv}-update"
            condition: UNSTABLE_OR_BETTER
            predefined-parameters: |
              deploy_id=${{BUILD_NUMBER}}

- project:
    name: at
    env: at
    nextenv: staging
    jobs:
      - "pipeline-{env}-deploy-transient"
      - "pipeline-{env}-test-transient"
      - "pipeline-{env}-teardown"

#- project:
#    name: staging
#    env: staging
#    nextenv: production
#    jobs:
#      - "{env}-update"
#      - "{env}-test"
#
#- project:
#    name: production
#    env: production
#    nextenv: fake
#    jobs:
#      - "{env}-update"
#      - "{env}-test"

- job:
    name: pipeline-fake-update
    node: master
